// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJc__kkzwkRkAojdW-sjleAqTMEFQAX54',
    appId: '1:39600448473:web:af5806223f6a6dc843efc8',
    messagingSenderId: '39600448473',
    projectId: 'png-game-da9ba',
    authDomain: 'png-game-da9ba.firebaseapp.com',
    storageBucket: 'png-game-da9ba.firebasestorage.app',
    measurementId: 'G-CBJF88ZCP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDoOAmhklMlJ7s_-VAMlAPwWq63wod1Ew',
    appId: '1:39600448473:android:c94943ea1da151ff43efc8',
    messagingSenderId: '39600448473',
    projectId: 'png-game-da9ba',
    storageBucket: 'png-game-da9ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqX2Lz-2goM4ebYsqaTBRTRustRq8tTcQ',
    appId: '1:39600448473:ios:a88c6a9bf5793b2b43efc8',
    messagingSenderId: '39600448473',
    projectId: 'png-game-da9ba',
    storageBucket: 'png-game-da9ba.firebasestorage.app',
    iosBundleId: 'com.example.pngGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqX2Lz-2goM4ebYsqaTBRTRustRq8tTcQ',
    appId: '1:39600448473:ios:a88c6a9bf5793b2b43efc8',
    messagingSenderId: '39600448473',
    projectId: 'png-game-da9ba',
    storageBucket: 'png-game-da9ba.firebasestorage.app',
    iosBundleId: 'com.example.pngGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJc__kkzwkRkAojdW-sjleAqTMEFQAX54',
    appId: '1:39600448473:web:9db5e1dcede3d91643efc8',
    messagingSenderId: '39600448473',
    projectId: 'png-game-da9ba',
    authDomain: 'png-game-da9ba.firebaseapp.com',
    storageBucket: 'png-game-da9ba.firebasestorage.app',
    measurementId: 'G-9VF3MGLXH4',
  );
}
