name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'nestjs-backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'nestjs-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./nestjs-backend

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './nestjs-backend/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Run Linter
      run: npm run lint

    - name: Run Tests
      run: npm run test

    - name: Build Application
      run: npm run build
